name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Download dependencies
      run: apt install qt6-base-dev qt6-declarative-dev
    - name: Build
      run: QMAKE=/usr/bin/qmake cargo build --verbose
