name: Rust
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download dependencies
        run: |
          sudo apt update -y
          sudo apt install -y qt6-base-dev qt6-declarative-dev qmake6
      - name: Build
        run: cargo build --verbose
